version: "3.9"

services:
  frontend:
    stdin_open: true
    container_name: rodrigojs.dev
    build:
      dockerfile: Dockerfile
      context: "./"
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - 3000:3000
